name: ChatUtils
version: '${project.version}'
main: org.gotitim.chatutils.Main
api-version: 1.13
softdepend: [ Vault ]
authors: [ gotitim ]
description: Customize your server chat messages!
permissions:
  cu.nick:
    default: true
    description: Ability to use /nick command (if not disabled)
  cu.msg:
    default: true
    description: Ability to use /msg
  cu.bypass_banword:
    default: op
    description: Players with this permission aren't chcked if they used banned word
  cu.bypass_chatlock:
    default: op
    description: Players with this permission can bypass chat lock
commands:
  cu:
    description: Main ChatUtils command
    aliases:
      - chatutils
      - chat
  msg:
    description: A customizable version of /msg
    aliases:
      - whisper
      - dm
    permission: ccm.msg